export { supabase } from './client'
export { useSupabase } from './hooks'
export { orderService as dbOrderService, type Order } from './database'
export { orderService, type Order as OrderType } from './orders'
export { productService, type Product } from './products'
export { storageService } from './storage'
export { categoryService, type CategoryImage } from './categories'
export { customerService, type Customer } from './customers'